name: rdp-windows

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
            
      - name: Clone tools
        run: git clone git@github.com:fkunn1326/github-ci.git .
        
      - name: Clone Backups
        run: git clone git@github.com:fkunn1326/ghvnc-secret.git backups
        
      - name: Setup IME
        run: |
          Invoke-Webrequest https://dl.google.com/japanese-ime/2.25.3700.0/googlejapaneseinput64.msi　-OutFile googleime.msi
          msiexec /i googleime.msi
      - name: Expand uvnc
        run:  Expand-Archive .\tools\uvnc.zip
        
      - name: Set config  
        run: Move-Item .\scripts\UltraVNC.ini .\uvnc\64 
        
      - name: Set TimeZone
        run: Set-TimeZone -id "Tokyo Standard Time"
      
      - name: Set Resolution
        run: .\scripts\Set-ScreenResolution.ps1
        
      - name: Set scale
        run: .\scripts\Set-Scale.ps1 1
        
      - name: Set ColorTheme
        run: Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize -Name AppsUseLightTheme -Value 0

      - name: Set Wallpaper
        run: set-itemproperty -path "HKCU:Control Panel\Desktop" -name WallPaper -value .\tools\wallpaper.jpg
        
      - name: Start Vnc
        run: start .\uvnc\64\winvnc.exe

      - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
              
      - name: Restore files
        run: .\scripts\Restore.ps1
                
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      
      - name: Backup files
        run: .\scripts\Backup.ps1
